HW_completed = (12)
Number_of_hours_spent = (1.5)
Course_name = ('Python')
Time_per_task = (Number_of_hours_spent / HW_completed)
print('Курс: Python, всего задач:',HW_completed,', затрачено часов:',Number_of_hours_spent, ', среднее время выполнения:',Time_per_task, 'часа.')